// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// nll_gmultmix
double nll_gmultmix(arma::vec beta, std::string mixture, std::string pi_fun, arma::mat Xlam, arma::vec Xlam_offset, arma::mat Xphi, arma::vec Xphi_offset, arma::mat Xdet, arma::vec Xdet_offset, Rcpp::IntegerVector k, arma::vec lfac_k, arma::cube lfac_kmyt, arma::cube kmyt, arma::vec y, arma::vec naflag, arma::mat fin, int nP, int nLP, int nPP, int nDP, int threads);
RcppExport SEXP _unmarked_nll_gmultmix(SEXP betaSEXP, SEXP mixtureSEXP, SEXP pi_funSEXP, SEXP XlamSEXP, SEXP Xlam_offsetSEXP, SEXP XphiSEXP, SEXP Xphi_offsetSEXP, SEXP XdetSEXP, SEXP Xdet_offsetSEXP, SEXP kSEXP, SEXP lfac_kSEXP, SEXP lfac_kmytSEXP, SEXP kmytSEXP, SEXP ySEXP, SEXP naflagSEXP, SEXP finSEXP, SEXP nPSEXP, SEXP nLPSEXP, SEXP nPPSEXP, SEXP nDPSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< std::string >::type mixture(mixtureSEXP);
    Rcpp::traits::input_parameter< std::string >::type pi_fun(pi_funSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Xlam(XlamSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Xlam_offset(Xlam_offsetSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Xphi(XphiSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Xphi_offset(Xphi_offsetSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Xdet(XdetSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Xdet_offset(Xdet_offsetSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type k(kSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lfac_k(lfac_kSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type lfac_kmyt(lfac_kmytSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type kmyt(kmytSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec >::type naflag(naflagSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type fin(finSEXP);
    Rcpp::traits::input_parameter< int >::type nP(nPSEXP);
    Rcpp::traits::input_parameter< int >::type nLP(nLPSEXP);
    Rcpp::traits::input_parameter< int >::type nPP(nPPSEXP);
    Rcpp::traits::input_parameter< int >::type nDP(nDPSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(nll_gmultmix(beta, mixture, pi_fun, Xlam, Xlam_offset, Xphi, Xphi_offset, Xdet, Xdet_offset, k, lfac_k, lfac_kmyt, kmyt, y, naflag, fin, nP, nLP, nPP, nDP, threads));
    return rcpp_result_gen;
END_RCPP
}
